#!/usr/bin/env python3
"""Assemble presentation/deck.md from presentation/deck_parts/*.md in storyboard order.

The parts are authored per owner-slice; the deck is the single source of truth the prompt
generator and the verifier read. Order comes from the slide ids in presentation/storyboard.md
(S01..S26 main flow, then B01..). Also reports the main-flow seconds total and any visual
that is missing from presentation/assets/.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from deckspec import parse  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PRES = ROOT / "presentation"
BUDGET = 1380


def storyboard_order() -> list[str]:
    ids = re.findall(r"^\| ([SB]\d{2}) \|", (PRES / "storyboard.md").read_text(encoding="utf-8"), re.M)
    return ids


def raw_sections(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    out: dict[str, str] = {}
    for m in re.finditer(r"^## ([SB]\d{2}) · .*?(?=^## [SB]\d{2} · |\Z)", text, re.M | re.S):
        out[m.group(1)] = m.group(0).rstrip() + "\n"
    return out


def main() -> int:
    order = storyboard_order()
    sections: dict[str, str] = {}
    for part in sorted((PRES / "deck_parts").glob("*.md")):
        for sid, body in raw_sections(part).items():
            if sid in sections:
                print(f"duplicate slide {sid} in {part.name}")
                return 1
            sections[sid] = body
    missing = [s for s in order if s not in sections]
    extra = [s for s in sections if s not in order]
    if missing or extra:
        print(f"missing from parts: {missing}\nnot in storyboard: {extra}")
        return 1
    header = ("# Deck spec\n\n"
              "Source of truth for the slides. Generated by tools/presentation/assemble_deck.py from\n"
              "presentation/deck_parts/*.md; edit the parts, not this file. Format: presentation/STRATEGY.md.\n\n")
    (PRES / "deck.md").write_text(header + "\n".join(sections[s] for s in order), encoding="utf-8")
    slides = parse(PRES / "deck.md")
    secs = sum(int(s.fields.get("seconds", 0)) for s in slides if not s.is_backup)
    absent = sorted({s.fields.get("visual", "") for s in slides
                     if s.fields.get("visual", "").startswith("assets/")
                     and not (PRES / s.fields["visual"]).exists()})
    print(f"deck.md: {len([s for s in slides if not s.is_backup])} main + "
          f"{len([s for s in slides if s.is_backup])} backup slides; main flow {secs} s "
          f"({'within' if secs <= BUDGET else 'OVER'} the {BUDGET} s budget)")
    if absent:
        print("visuals missing from presentation/assets/: " + ", ".join(absent))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
