#!/usr/bin/env python3
"""Markdown -> Typst for hw/docs/hardware_report.md.

The Markdown file is the source the hardware report is edited in; the PDF the
archive ships needs a committed, reproducible origin, so report/build.sh runs
this to emit hw/docs/hardware_report.typ and compiles that with Typst. The
subset handled is exactly what the report uses: ATX headings (1-3), paragraphs,
bullet lists (two indent levels), numbered lists, pipe tables with alignment
rows, horizontal rules, images, links, **bold**, *italic* and `code` spans.
Anything else passes through escaped, so an unsupported construct shows up
as literal text in the PDF rather than silently vanishing.

    python3 tools/md2typ.py hw/docs/hardware_report.md hw/docs/hardware_report.typ
"""
import os
import re
import sys

HEADER = r'''// GENERATED by tools/md2typ.py from %(src)s -- edit the Markdown, not this file.
#set document(title: "%(title)s", author: ("Yuval Kogan", "Matan Cohen"))
#set page(paper: "a4", margin: (x: 18mm, y: 17mm), numbering: "1",
  header: context if counter(page).get().first() > 1 {
    text(size: 8pt, fill: rgb("#18344a"))[HWSW Final Project #h(1fr) %(title)s]
  })
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")
#set par(justify: false, leading: 0.55em, spacing: 0.65em)
#show raw: set text(size: 8.5pt)
#show heading.where(level: 1): set text(size: 17pt, fill: rgb("#18344a"))
#show heading.where(level: 2): set text(size: 13pt, fill: rgb("#18344a"))
#show heading.where(level: 3): set text(size: 11pt, fill: rgb("#18344a"))
#show link: set text(fill: rgb("#185b87"))
#set table(inset: 4pt, stroke: 0.35pt + rgb("#bdcbd5"),
  fill: (x, y) => if y == 0 { rgb("#eef3f7") })
#show table: set text(size: 8.5pt)
#show table: set par(justify: false)
'''

# Characters Typst would otherwise interpret as markup.
_ESC = str.maketrans({c: '\\' + c for c in '\\#$@<>_*~"[]'})


def esc(s):
    return s.translate(_ESC)


INLINE = re.compile(
    r'`([^`]*)`'                      # code span
    r'|!\[([^\]]*)\]\(([^)]+)\)'      # image
    r'|\[([^\]]+)\]\(([^)]+)\)'       # link
    r'|\*\*(.+?)\*\*'                 # bold
    r'|\*(.+?)\*'                     # italic
)


def inline(s):
    out, i = [], 0
    for m in INLINE.finditer(s):
        out.append(esc(s[i:m.start()]))
        code, img_alt, img_src, link_txt, link_url, bold, ital = m.groups()
        if code is not None:
            out.append('#raw("%s")' % code.replace('\\', '\\\\').replace('"', '\\"'))
        elif img_src is not None:
            out.append('#figure(image("%s", width: 100%%), caption: [%s])'
                       % (img_src, esc(img_alt)))
        elif link_url is not None:
            out.append('#link("%s")[%s]' % (link_url, inline(link_txt)))
        elif bold is not None:
            out.append('#strong[%s]' % inline(bold))
        else:
            out.append('#emph[%s]' % inline(ital))
        i = m.end()
    out.append(esc(s[i:]))
    return ''.join(out)


def table_block(rows, out):
    header, align_row, body = rows[0], rows[1], rows[2:]
    n = len(header)
    align = []
    for cell in align_row + [''] * (n - len(align_row)):
        c = cell.strip()
        align.append('right' if c.endswith(':') and not c.startswith(':') else 'left')
    # Label column sized to content; with four or more columns the rest share
    # the width equally, otherwise a long cell in an `auto` column squeezes
    # its neighbours off the page.
    if n <= 2:
        widths = '1fr, 1fr'
    elif n == 3:
        widths = 'auto, auto, 1fr'
    else:
        widths = ', '.join(['auto'] + ['1fr'] * (n - 1))
    out.append('#table(columns: (%s), align: (%s),' % (widths, ', '.join(align)))
    out.append('  table.header(%s),' % ', '.join(
        '[#strong[%s]]' % inline(c.strip()) for c in header))
    for r in body:
        r = (r + [''] * n)[:n]
        out.append('  %s,' % ', '.join('[%s]' % inline(c.strip()) for c in r))
    out.append(')')
    out.append('')


def convert(md, src):
    lines = md.splitlines()
    title = next((l[2:].strip() for l in lines if l.startswith('# ')), 'Hardware report')
    out = [HEADER % {'src': src, 'title': esc(title)}]
    para, table = [], []

    def flush_para():
        if para:
            out.append(inline(' '.join(para)))
            out.append('')
            para.clear()

    def flush_table():
        if table:
            table_block(list(table), out)
            table.clear()

    for line in lines:
        if line.lstrip().startswith('|'):
            flush_para()
            table.append(line.strip().strip('|').split('|'))
            continue
        flush_table()
        m = re.match(r'^(#{1,3}) (.*)', line)
        if m:
            flush_para()
            out.append('%s %s' % ('=' * len(m.group(1)), inline(m.group(2))))
            out.append('')
            continue
        if re.match(r'^-{3,}\s*$', line):
            flush_para()
            out.append('#line(length: 100%, stroke: 0.4pt + gray)')
            out.append('')
            continue
        m = re.match(r'^(\s*)(\d+)\. (.*)', line)
        if m:
            flush_para()
            out.append('%s+ %s' % (m.group(1), inline(m.group(3))))
            continue
        m = re.match(r'^(\s*)- (.*)', line)
        if m:
            flush_para()
            out.append('%s- %s' % (m.group(1), inline(m.group(2))))
            continue
        if not line.strip():
            flush_para()
            out.append('')
            continue
        if para or not out or out[-1] == '' or not out[-1].startswith(('-', '+', ' ')):
            para.append(line.strip())
        else:
            # continuation of a list item: keep it attached to the item
            out[-1] += ' ' + inline(line.strip())
    flush_para()
    flush_table()
    return '\n'.join(out) + '\n'


def main():
    if len(sys.argv) != 3:
        sys.exit('usage: md2typ.py <in.md> <out.typ>')
    src, dst = sys.argv[1], sys.argv[2]
    # Provenance line goes into a committed file, so keep it machine-independent.
    rel = os.path.relpath(src, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
    with open(src, encoding='utf-8') as fh:
        md = fh.read()
    with open(dst, 'w', encoding='utf-8') as fh:
        fh.write(convert(md, rel))


if __name__ == '__main__':
    main()
