#!/usr/bin/env python3
"""Generate the front-end static reservation table (uArch §7/§8) as a SystemVerilog include.

Runs the greedy schedule of schedule_model.py (3 add / 3 mul / sqrt / rcp) and emits the issue
slot of every *front-end* op — sub, square, dsq adds, sqrt, d3, rcp, mag, b1m/b2m, force terms —
with its unit binding, as localparam tables in rtl/grape_sched_rom.svh. Accumulate and integrate
ops are NOT in the table: they issue dynamically, in order, into ADD/MUL slots the table leaves
free, gated by the per-(body, component) scoreboard (uArch §3.3) — the pair-list-independent
static alternative was modelled at 132/136 cycles > K1 128 and rejected.

Table format (one row per issue event, sorted by cycle):
  SCHED_CYCLE[e]  — issue cycle within the step (0-based, cycle 0 = first FORCE cycle)
  SCHED_UNIT[e]   — unit id: 0..2 ADD, 3..5 MUL, 6 SQRT, 7 RCP
  SCHED_PAIR[e]   — pair slot 0..9 (issue suppressed at runtime when >= NPAIRS)
  SCHED_TAG[e]    — op tag (TAG_* localparams; identifies operands and dst scratch)

    python3 hw/grape_pipeline/docs/gen_reservation.py       # rewrites rtl/grape_sched_rom.svh
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import schedule_model as m

TAGS = ["SUB_X", "SUB_Y", "SUB_Z", "SQ_X", "SQ_Y", "SQ_Z", "A1", "DSQ", "SQRT", "D3", "RCP",
        "MAG", "B1M", "B2M", "F_I_X", "F_I_Y", "F_I_Z", "F_J_X", "F_J_Y", "F_J_Z"]


def build_and_schedule():
    ops = m.build_ops()
    # tag front-end ops: ops are appended per pair in build_ops() order (26 per pair: 20 front-end
    # + 6 accumulate), then 30 integrate ops.
    per_pair = 26
    fe_index = {}                       # op id -> (pair, tag)
    order = ["SUB_X", "SUB_Y", "SUB_Z", "SQ_X", "SQ_Y", "SQ_Z", "A1", "DSQ", "SQRT", "D3",
             "RCP", "MAG", "B1M", "B2M", "F_I_X", "F_I_Y", "F_I_Z", "F_J_X", "F_J_Y", "F_J_Z"]
    for k in range(len(m.PAIRS)):
        base = k * per_pair
        for n, tag in enumerate(order):
            fe_index[base + n] = (k, tag)
    # greedy schedule identical to schedule_model.schedule(), but recording issue cycle + unit
    lat = {"ADD": m.ADD_L, "MUL": m.MUL_L, "SQRT": m.SQRT_L, "RCP": m.RCP_L}
    cap = {"ADD": 3, "MUL": 3, "SQRT": 1, "RCP": 1}
    unit_base = {"ADD": 0, "MUL": 3, "SQRT": 6, "RCP": 7}
    ii = {"SQRT": 0, "RCP": 0}
    done = [None] * len(ops)
    issue = {}
    t = 0
    pending = set(range(len(ops)))
    ci = {}
    while pending:
        used = {k: 0 for k in cap}
        for i in sorted(pending):
            o = ops[i]
            u = o["u"]
            if used[u] >= cap[u] or (u in ii and t < ii[u]):
                continue
            if any(done[d] is None or done[d] > t for d in o["d"]):
                continue
            if o["c"] is not None:
                li = ci.get(o["c"], -1)
                if any(j in pending and j < i and ops[j]["c"] == o["c"] for j in range(li + 1, i)):
                    continue
            done[i] = t + lat[u]
            issue[i] = (t, unit_base[u] + used[u])
            used[u] += 1
            if u in ii:
                ii[u] = t + (m.SQRT_II if u == "SQRT" else m.RCP_II)
            if o["c"] is not None:
                ci[o["c"]] = i
            pending.discard(i)
        t += 1
    step = max(done) + m.COMMIT + m.FSM
    rows = sorted((issue[i][0], issue[i][1], fe_index[i][0], fe_index[i][1])
                  for i in fe_index)
    return rows, step


def emit(rows, step):
    out = pathlib.Path(__file__).parents[1] / "rtl" / "grape_sched_rom.svh"
    n = len(rows)
    lines = ["// GENERATED by docs/gen_reservation.py from docs/schedule_model.py — do not edit.",
             f"// Front-end static reservation table: {n} issue events, modelled step = {step} cycles",
             "// (nominal latencies; worst corner 127). Units: 0..2 ADD, 3..5 MUL, 6 SQRT, 7 RCP.",
             f"localparam int SCHED_EVENTS = {n};",
             f"localparam int SCHED_STEP_CYCLES = {step};"]
    for tag_i, tag in enumerate(TAGS):
        lines.append(f"localparam int TAG_{tag} = {tag_i};")
    # Yosys rejects unpacked localparam arrays: emit constant case-functions instead.
    def fn(name, vals, w):
        lines.append(f"function automatic logic [{w-1}:0] {name}(input int e);")
        lines.append(f"    logic [{w-1}:0] r;")
        lines.append(f"    r = {w}'d0;")
        lines.append("    case (e)")
        for i, v in enumerate(vals):
            lines.append(f"        {i}: r = {w}'d{v};")
        lines.append(f"        default: r = {w}'d0;")
        lines.append("    endcase")
        lines.append(f"    {name} = r;")
        lines.append("endfunction")
    fn("sched_cycle", [r[0] for r in rows], 8)
    fn("sched_unit", [r[1] for r in rows], 3)
    fn("sched_pair", [r[2] for r in rows], 4)
    fn("sched_tag", [TAGS.index(r[3]) for r in rows], 5)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {n} events, step {step}")


if __name__ == "__main__":
    rows, step = build_and_schedule()
    assert len(rows) == 200, len(rows)          # 20 front-end ops x 10 pairs
    emit(rows, step)
