"""T3 -- fully unrolled / register-allocated advance() (see gen_unrolled.py).

Three flavours, all generated by the same N-generic emitter:
  t3   : sqrt route,      mass literals             (fast, ~2ulp off stock)
  t3e  : pow route,       mass literals             (BIT-IDENTICAL to stock)
  t3f  : sqrt + folded m*dt hoisted out of the loop (fastest, reassociated)
"""
from math import sqrt as _sqrt

import gen_unrolled
from common import fresh_bodies, pair_indices, offset_momentum_aos

NAME = "T3 unrolled"

_MASSES = None
_ADV = {}


def _adv(masses, exact, fold):
    key = (tuple(masses), exact, fold)
    fn = _ADV.get(key)
    if fn is None:
        fn = _ADV[key] = gen_unrolled.build(
            list(masses), pair_indices(len(masses)),
            exact=exact, fold_mass=fold)
    return fn


def _make(exact, fold):
    def make_state():
        bodies = fresh_bodies()
        offset_momentum_aos(bodies)
        masses = [b[2] for b in bodies]
        return (bodies, _adv(masses, exact, fold),
                [(bodies[i], bodies[j])
                 for (i, j) in pair_indices(len(bodies))])

    def advance(st, dt, n):
        st[1](st, dt, n)

    return make_state, advance


make_state, advance = _make(False, False)
make_state_exact, advance_exact = _make(True, False)
make_state_fold, advance_fold = _make(False, True)


def energy(st):
    bodies = st[0]
    pairs = st[2]
    sqrt = _sqrt
    e = 0.0
    for (r1, v1, m1), (r2, v2, m2) in pairs:
        dx = r1[0] - r2[0]
        dy = r1[1] - r2[1]
        dz = r1[2] - r2[2]
        e -= (m1 * m2) / sqrt(dx * dx + dy * dy + dz * dz)
    for r, (vx, vy, vz), m in bodies:
        e += m * (vx * vx + vy * vy + vz * vz) / 2.
    return e


def energy_exact(st):
    """Stock's exact FP sequence (`** 0.5`), for the bit-identical flavour."""
    bodies = st[0]
    pairs = st[2]
    e = 0.0
    for (r1, v1, m1), (r2, v2, m2) in pairs:
        dx = r1[0] - r2[0]
        dy = r1[1] - r2[1]
        dz = r1[2] - r2[2]
        e -= (m1 * m2) / ((dx * dx + dy * dy + dz * dz) ** 0.5)
    for r, (vx, vy, vz), m in bodies:
        e += m * (vx * vx + vy * vy + vz * vz) / 2.
    return e


def dump(st):
    out = []
    for (r, v, m) in st[0]:
        out.extend(r)
        out.extend(v)
        out.append(m)
    return out
